/* Ενδεικτικά λήμματα για τις υπόλοιπες εγγραφές (αγγλική Wikipedia, ή ελληνική με πρόθεμα 'el:').
   Όπου δεν υπάρχει λήμμα για το ίδιο το πιάτο, χρησιμοποιείται το πιο κοντινό (κύριο υλικό ή συγγενική συνταγή). */
Object.assign(WP, {
/* καφές & ροφήματα */
piccolo:'Latte',caramelmacchiato:'Latte macchiato',breve:'Breve',kafesgala:'Coffee milk',shakerato:'Caffè shakerato',icedmocha:'Caffè mocha',v60:'Pour-over coffee',kaffe_kardamo:'Turkish coffee',baileyscoffee:'Irish coffee',pharisaer:'Pharisäer',tzintzer:'Ginger tea',kanellogaryfallo:'Cinnamon',leukisokolata:'White chocolate',kryasokolata:'Chocolate milk',sokolatamaya:'Hot chocolate',goldenmilk:'Turmeric',galameli:'Milk',zestomilo:'Apple cider',vyssinada:'Prunus cerasus',soumada:'Orgeat syrup',marocchino:'Marocchino',conmiel:'Latte',caffecrema:'Caffè crema',iceshot:'Iced coffee',flashbrew:'Iced coffee',cafecalva:'Calvados',hazelnutlatte:'Latte',romano:'Espresso',conpanna:'Espresso con panna',borgia:'Caffè mocha',nitro:'Cold brew coffee',mazagran:'Mazagran (coffee)',freddomastiha:'Iced coffee',decaf:'Decaffeination',yazdi:'Turkish coffee',doubledouble:'Double-double (coffee)',
/* ψητά, κυνήγι */
tagliata:'Steak',kontosouvli:'el:Κοντοσούβλι',fileto_xoirino:'Pork tenderloin',paidakia:'Lamb and mutton',kleftikopsito:'Leg of lamb',kotopoulofileto:'Chicken breast',mpoutiasxaras:'Barbecue chicken',mpiftekia:'Hamburger',spalasouvla:'Souvla',kotopoulokempap:'Kebab',bifteki_gemisto:'Hamburger',trygonia:'Pigeon as food',kotsyfia:'-',kounelilemonato:'Rabbit meat',kounelisouvla:'Rabbit meat',
/* μαγειρευτά */
arnilemonato:'Leg of lamb',kotopoulofournou:'Roast chicken',kotopoulomexylopites:'el:Χυλοπίτες',soutzoukakia:'el:Σουτζουκάκια',kokkinisto:'Stifado',xoirinoselino:'Avgolemono',moscharilemonato:'Pot roast',kokoraskrasatos:'Coq au vin',giouvarlakia:'Avgolemono',sofrito:'el:Σοφρίτο',arakas:'Pea',mpamies:'Okra',agkinareslapolita:'Artichoke',patatesgiaxni:'Potato',prasoryzo:'Leek',revithada:'Chickpea',vrasto:'Pot-au-feu',revithosoupa:'Chickpea',makaroniakima:'Spaghetti',mpiftekiafournou:'Hamburger',arnigastra:'Leg of lamb',katsikaki:'Goat meat',arnifrikase:'Fricassee',kotopoulokokkinisto:'Chicken as food',kolokythakiagemista:'Stuffed zucchini',kotopoulompamies:'Okra',xoirinodamaskina:'Prune',kreatosoupa:'Beef noodle soup',manestra:'Orzo',laxanoryzo:'Cabbage',sofigado:'Rabbit meat',mastelo:'Lamb and mutton',gidavrasti:'Goat meat',xoirinopraso:'Leek',xortosoupa:'Vegetable soup',broccolicheddar:'Broccoli',arakososoupa:'Pea soup',
/* θαλασσινά */
lavrakialati:'Salt crust',marida:'Picarel',skoumpri:'Mackerel as food',psariplaki:'el:Ψάρι πλακί',kakavia:'Fish soup',kalamarigemisto:'Squid as food',xtapodistifado:'Stifado',garidessaganaki:'Saganaki',garidomakaronada:'el:Γαριδομακαρονάδα',astakomakaronada:'el:Αστακομακαρονάδα',thalassinoryzoto:'Risotto',xtapodikofto:'Octopus as food',gavrosmarinatos:'Boquerones en vinagre',lakerda:'el:Λακέρδα',sardelapasti:'Sardines as food',bourdeto:'Bourdeto',tonos:'Tuna',galeos:'Shark meat',sardelesladokolla:'Sardines as food',soupiorizo:'Black rice (dish)',mydopilafo:'Mussel',garidesgiouvetsi:'Giouvetsi',kydonia:'Oyster',fagkri:'Pagrus pagrus',spetsiota:'Fish as food',garidessxaras:'Shrimp',carpacciolavraki:'Carpaccio',thalassinisalata:'Seafood salad',keftedesmpakaliarou:'Salt cod',
/* μεζέδες, τυριά */
fetapsiti:'Feta',feta_ladorigani:'Feta',tyropitakia:'Tiropita',ntomatokeftedes:'el:Ντοματοκεφτέδες',kolokythokeftedes:'Zucchini fritter',kolokythakiatiganita:'Fried zucchini',piperiesflorinis:'Florina pepper',kafteres:'Chili pepper',manitaria:'Pleurotus ostreatus',patatesmeavga:'Fried egg',spanakopitakia:'Spanakopita',mpekrimeze:'el:Μπεκρή μεζέ',spetzofai:'el:Σπετζοφάι',sykotakia:'Liver (food)',kavourmas:'el:Τηγανιά (φαγητό)',mydiasaganaki:'Mussel',axinosalata:'Sea urchin',kreatopitakia:'Meat pie',fetapane:'Feta',splinantero:'Kokoretsi',tyrokroketes:'Croquette',patatokeftedes:'Potato pancake',bourekakia:'Börek',sfakiani:'el:Σφακιανή πίτα',xortopita:'Hortopita',stakaavga:'Staka',saligkaria:'Escargot',antzougies:'Anchovies as food',loutza:'Louza',toursi:'Pickled cucumber',gopes:'Boops boops',revithokeftedes:'Falafel',kremmydokeftedes:'Onion',melitzanesfeta:'Eggplant',manitariagemista:'Stuffed mushrooms',xortatsigariasta:'Horta (food)',patatesoftes:'Baked potato',loukanikokrasato:'Loukaniko',fetapipeati:'Feta',xtapodiliasto:'Octopus as food',soupiestiganites:'Cuttlefish',garidestiganites:'Shrimp',sardelesampelofylla:'Sardines as food',arayes:'Kofta',fava:'el:Φάβα',xtypiti:'el:Χτυπητή',
/* σαλάτες, συνοδευτικά, σάλτσες */
salatamarouli:'Lettuce',pantzarosalata:'Beetroot',rokaparmezana:'Eruca vesicaria',fasolosalata:'Black-eyed pea',kritikisalata:'Dakos',politiki:'Coleslaw',kaparosalata:'Caper',tonosalata:'Tuna salad',ampelofasoula:'Yardlong bean',kounoupidi:'Cauliflower',aggourontomata:'Tomato',roka_syka:'Fig',fakessalata:'Lentil',kritharakisalata:'Orzo',xoriatikiparallagi:'Greek salad',kinoa:'Quinoa',spanakifraoula:'Spinach salad',garidaavokanto:'Avocado',pastaelias:'Tapenade',tyrosalata:'Tirokafteri',patatesfournou:'Roast potato',babypatates:'Roast potato',patatesvrastes:'Boiled potato',basmati:'Basmati',makaronia_voutyro:'Spaghetti',kritharotto:'Orzo',xorta:'Horta (food)',lachanikasxaras:'Grilled vegetables',lachanikasote:'Stir frying',pita_souvlaki:'Pita',skordopsomo:'Garlic bread',psomi_ladirigani:'Bruschetta',saltsantomata:'Tomato sauce',ladolemono:'Olive oil',ladoxido:'Vinaigrette',saltsapiperiou:'Peppercorn sauce',moustardameli:'Honey mustard',kremmydipaprika:'Red onion',sosmoustardas:'Honey mustard',sosgiaourti:'Garlic sauce',kafteri_saltsa:'Hot sauce',rosesos:'Marie Rose sauce',mayoskordo:'Aioli',
/* πρωινό, σνακ */
avgavrasta:'Boiled egg',sfougato:'Frittata',tost:'Toast sandwich',klabsandwich:'Club sandwich',kreatopita:'Meat pie',tiganites:'Pancake',frouta:'Fruit salad',paximadiladi:'Paximadi',mouslibowl:'Açaí na tigela',kritsinia:'Grissini',kalasouna:'Onion pie',patsavouropita:'Tiropita',
/* σουβλατζίδικο */
tylixtompifteki:'Pita',tylixtoloukaniko:'Loukaniko',tylixtoxaloumi:'Halloumi',clubpita:'Club sandwich',kalamakipsomaki:'Souvlaki',poikilia:'Mixed grill',kotopoulonoodles:'Chow mein',quattroformaggi:'Quattro formaggi',
/* γλυκά */
sekerpare:'Şekerpare',mousfalevria:'el:Μουσταλευριά',mousesokolatas:'Chocolate mousse',gianourtivyssino:'Strained yogurt',galaktoboureko_kremaxoris:'Pastry cream',keikmarmpre:'Marble cake',sokolatopita:'Chocolate cake',kydoni:'Quince',nerantzaki:'Spoon sweets',amygdalota:'Amygdalota',galatopita:'Galatopita',pagotokaimaki:'Dondurma',pastaflora:'Pasta frola',kormos:'Chocolate salami',trigona:'Cream horn',keiklemoni:'Lemon cake',giaourtopita:'Yogurt cake',lemonopita:'Lemon meringue pie',kolokythopita:'Pumpkin pie',tartafrouton:'Fruit tart',kopegxagi:'Baklava',moustokouloura:'Petimezi',petimezopita:'Petimezi',melitinia:'Melitinia',lagana:'el:Λαγάνα',kolokythoanthoi:'Squash blossom',
/* κρασιά, μπύρες, ποτά */
malagouzia:'Wine',vilana:'Wine',robola:'Kefalonia',liatiko:'Red wine',limnio:'Lemnos',mavrotragano:'Santorini',xyma:'Carafe',moschatosamou:'Muscat (grape)',vidiano:'White wine',athiri:'White wine',zitsa:'Sparkling wine',moschatolimnou:'Muscat of Alexandria',sherry:'Sherry',ellinikes:'Lager',keo:'Beer glassware',alkoolfree:'Low-alcohol beer',
amarettosour:'Amaretto',paperplane:'Paper Plane (cocktail)',ginbasil:'Basil',mastihatonic:'Gin and tonic',ouzolemonada:'Ouzo',tsipourosour:'Whiskey sour',metaxasour:'Sidecar (cocktail)',kitrospritz:'Spritz Veneziano',fruitpunch:'Punch (drink)',ouzo:'el:Ούζο',rakomelo:'el:Ρακόμελο',limoncello:'el:Λιμοντσέλο',vyssinoliker:'Cherry liqueur',campari:'Aperol',beesknees:"Bee's knees (cocktail)",rustynail:'Rusty nail (cocktail)',lastword:'Last Word (cocktail)',mastihamojito:'Mojito',ouzosour:'Whiskey sour',tentoura:'el:Τεντούρα',caipiroska:'Caipiroska',malibupine:'Malibu (rum)',ginfizz:'Gin fizz',mudslide:'Mudslide',rossini:'Rossini (cocktail)',tequilashot:'Tequila',icedlemonmint:'Iced tea',frouto_fizz:'Strawberry',frangelico:'Hazelnut',aygoliker:'Eggnog',souma:'Souma'
});
/* διορθώσεις μετά τον μαζικό έλεγχο */
Object.assign(WP,{breve:'Latte',decaf:'Coffee',caffecrema:'Espresso',conpanna:'Whipped cream',shakerato:'Iced coffee',mazagran:'Iced coffee',doubledouble:'Coffee',stakaavga:'Fried egg',soupiorizo:'Arròs negre',kolokythokeftedes:'Zucchini',kolokythakiatiganita:'Zucchini',xortopita:'Spanakopita',lachanikasxaras:'Bell pepper',kalasouna:'Onion',galatopita:'Custard',giaourtopita:'Revani',sherry:'Fortified wine',ouzo:'Pastis',ouzolemonada:'Pastis',souma:'Pomace brandy',xyma:'Wine',campari:'Negroni',melitinia:'Kalitsounia',vyssinoliker:'Liqueur',mousfalevria:'Must',mpekrimeze:'el:Τηγανιά (φαγητό)',kontosouvli:'Souvla',psariplaki:'Fish as food',garidomakaronada:'Shrimp',ntomatokeftedes:'Fritter',sfakiani:'Mizithra'});
WP.kotsyfia='Quail as food';
