/* Ακριβή λήμματα αγγλικής Wikipedia ανά συνταγή – για σωστή (ενδεικτική) φωτογραφία. Φορτώνονται μόνο μετά από συγκατάθεση. */
window.WP = {
/* καφές */
espresso:'Espresso',ristretto:'Ristretto',lungo:'Lungo',doppio:'Doppio',americano:'Caffè Americano',longblack:'Long black',macchiato:'Caffè macchiato',cortado:'Cortado',cappuccino:'Cappuccino',latte:'Latte',flatwhite:'Flat white',lattemacchiato:'Latte macchiato',mocha:'Caffè mocha',whitemocha:'Caffè mocha',affogato:'Affogato',ellinikos:'Greek coffee',ellinikosxovoli:'Turkish coffee',tourkikos:'Turkish coffee',arabikos:'Arabic coffee',frape:'Frappé coffee',freddoespresso:'Iced coffee',freddocappuccino:'Iced coffee',freddolatte:'Iced coffee',coldbrew:'Cold brew coffee',icedlatte:'Iced coffee',icedamericano:'Iced coffee',dalgona:'Dalgona coffee',frappuccino:'Frappuccino',filtrou:'Drip coffee',chemex:'Chemex Coffeemaker',frenchpress:'French press',aeropress:'AeroPress',moka:'Moka pot',syphon:'Vacuum coffee maker',instant:'Instant coffee',vietnamiced:'Vietnamese iced coffee',eggcoffee:'Egg coffee',cafedeolla:'Café de olla',cafecubano:'Café Cubano',cortadito:'Cortado',bombon:'Café bombón',viennois:'Vienna coffee',yuanyang:'Yuenyeung',irish:'Irish coffee',corretto:'Caffè corretto',carajillo:'Carajillo',barraquito:'Barraquito',redeye:'Red eye (drink)',aulait:'Café au lait',pumpkinspice:'Pumpkin spice latte',eiskaffee:'Eiskaffee',espressotonic:'Espresso',
/* ροφήματα */
mauro:'Black tea',earlgrey:'Earl Grey tea',englishbreakfast:'English breakfast tea',prasino:'Green tea',leuko:'White tea',oolong:'Oolong',matcha:'Matcha',matchalatte:'Matcha',chai:'Masala chai',icedtea:'Iced tea',bubbletea:'Bubble tea',rooibos:'Rooibos',tsaivounou:'Sideritis',xamomili:'Chamomile',faskomilo:'Salvia officinalis',diktamo:'Origanum dictamnus',menta:'Mentha spicata',louiza:'Aloysia citrodora',tilio:'Linden tea',zestisokolata:'Hot chocolate',pixtisokolata:'Hot chocolate',salepi:'Salep',lemonada:'Lemonade',portokalada:'Orange juice',milkshake:'Milkshake',smoothiebanana:'Smoothie',smoothietropic:'Smoothie',ayran:'Ayran',kombucha:'Kombucha',ginger_beer:'Ginger beer',
/* σουβλατζίδικο / fast food */
gyros:'Gyros',pitogyroxoirino:'Gyros',pitogyrokotopoulo:'Gyros',gyroskotopoulo:'Gyros',doner:'Doner kebab',tylixtokalamaki:'Souvlaki',tylixtokotopoulo:'Souvlaki',tylixtokempap:'Kebab',tylixtofalafel:'Falafel',souvlakikyprou:'Souvlaki',seftalia:'Sheftalia',meridagyros:'Gyros',meridakalamakia:'Souvlaki',falafel:'Falafel',shawarma:'Shawarma',burrito:'Burrito',tacos:'Al pastor',hotdog:'Hot dog',smashburger:'Hamburger',baconburger:'Bacon cheeseburger',chickenburger:'Chicken sandwich',veggieburger:'Veggie burger',burger:'Hamburger',margherita:'Pizza Margherita',pepperoni:'Pepperoni',pitsaspecial:'Pizza',zymipitsas:'Pizza',calzone:'Calzone',friedchicken:'Fried chicken',nuggets:'Chicken nugget',philly:'Cheesesteak',blt:'BLT',panini:'Panini (sandwich)',bagel:'Bagel and cream cheese',croquemonsieur:'Croque monsieur',padthai:'Pad thai',friedrice:'Fried rice',springrolls:'Spring roll',sushi:'Sushi',ramen:'Ramen',nachos:'Nachos',guacamole:'Guacamole',onionrings:'Onion ring',mozzarellasticks:'Mozzarella sticks',loadedfries:'Cheese fries',quesadilla:'Quesadilla',popcorn:'Popcorn',kreparmyri:'Crêpe',
/* ψητά */
mprizolamoschari:'Steak',ribeye:'Rib eye steak',tomahawk:'Rib eye steak',tbone:'T-bone steak',fileto:'Beef tenderloin',picanha:'Picanha',souvlakimoschari:'Souvlaki',mprizolaxoirini:'Pork chop',kalamaki:'Souvlaki',kontosouvli:'Kontosouvli',panseta:'Pork belly',pansetasouvlas:'Porchetta',porchetta:'Porchetta',paidakiaxoirina:'Pork ribs',kotsi:'Schweinshaxe',xoirinosouvlas:'Lechon',gourounopoulo:'Suckling pig',kokoretsi:'Kokoretsi',arnisouvlas:'Souvla',souvlakiarni:'Souvlaki',kotosouvlaki:'Souvlaki',ftergoules:'Buffalo wing',kotopoulosouvlas:'Rotisserie chicken',mpiftekia:'Biftekia',kempap:'Kebab',loukanikoxoriatiko:'Loukaniko',
/* κυνήγι */
lagosstifado:'Stifado',kounelistifado:'Stifado',agriogourouno:'Wild boar',agriogourounosouvla:'Wild boar',zarkadi:'Venison',elafistifado:'Venison',perdika:'Partridge',ortykia:'Quail as food',fasianos:'Pheasant',agriopapia:"Canard à l'orange",mpekatsa:'Woodcock',
/* μαγειρευτά */
mousakas:'Moussaka',pastitsio:'Pastitsio',giouvetsi:'Giouvetsi',kleftiko:'Kleftiko',gemista:'Gemista',briam:'Briam',papoutsakia:'Papoutsakia',imam:'Imam bayildi',gigantesfournou:'Gigantes plaki',soutzoukakia:'Soutzoukakia',kokkinisto:'Kokkinisto',stifado:'Stifado',ntolmades:'Cabbage roll',giouvarlakia:'Giouvarlakia',kokoraskrasatos:'Pastitsada',fasolakia:'Green bean',fasolada:'Fasolada',fakes:'Lentil soup',kotosoupa:'Avgolemono',patsas:'Patsas',trachanas:'Tarhana',magiritsa:'Magiritsa',lazania:'Lasagna',kanelonia:'Cannelloni',spanakoryzo:'Spanakorizo',ntomatosoupa:'Tomato soup',kremmydosoupa:'French onion soup',manitarosoupa:'Cream of mushroom soup',kolokythosoupa:'Pumpkin soup',karotosoupa:'Carrot soup',prasopatata:'Vichyssoise',broccolicheddar:'Broccoli cheese soup',minestrone:'Minestrone',gazpacho:'Gazpacho',tarator:'Tarator',borsch:'Borscht',pho:'Pho',tomyum:'Tom yum',misosoupa:'Miso soup',goulash:'Goulash',harira:'Harira',merjimek:'Lentil soup',laksa:'Laksa',wonton:'Wonton',chickennoodle:'Chicken soup',gumbo:'Gumbo',sopadeajo:'Garlic soup',mulligatawny:'Mulligatawny',
/* θαλασσινά */
tsipoura:'Gilt-head bream',tsipourafournou:'Gilt-head bream',mparmpounia:'Red mullet',gavrostiganitos:'Anchovies as food',sardelessxaras:'Sardines as food',xifias:'Swordfish',solomos:'Salmon as food',kakavia:'Kakavia',psarosoupa:'Fish soup',mpakaliaros:'Salt cod',xtapodisxaras:'Octopus as food',xtapodixidato:'Octopus as food',kalamaria:'Squid as food',fritomisto:'Fritto misto',soupiesspanaki:'Cuttlefish',mydia:'Moules marinières',paella:'Paella',fishchips:'Fish and chips',moulesfrites:'Moules-frites',bouillabaisse:'Bouillabaisse',ceviche:'Ceviche',crabcakes:'Crab cake',lobsterroll:'Lobster roll',clamchowder:'Clam chowder',vongole:'Spaghetti alle vongole',fideua:'Fideuà',xtapodifeira:'Pulpo a la gallega',solemeuniere:'Sole meunière',bacalhau:'Bacalhau',astakosxaras:'Lobster',karavides:'Nephrops norvegicus',xtenia:'Scallop',prawncocktail:'Prawn cocktail',mydiagemista:'Midye dolma',avgotaracho:'Bottarga',
/* μεζέδες, σαλάτες, αλοιφές */
saganaki:'Saganaki',mpougiourdi:'Bouyiourdi',xaloumi:'Halloumi',keftedakia:'Keftedes',ntolmadakia:'Dolma',elies:'Kalamata olive',tzatziki:'Tzatziki',taramosalata:'Taramasalata',melitzanosalata:'Melitzanosalata',fava:'Fava (Santorini)',skordalia:'Skordalia',tyrokafteri:'Tirokafteri',xoumous:'Hummus',babaganoush:'Baba ghanoush',mouxamara:'Muhammara',ajvar:'Ajvar',kibbeh:'Kibbeh',cevapi:'Ćevapi',lahmacun:'Lahmacun',arayes:'Arayes',kopanisti:'Kopanisti',katiki:'Katiki Domokou',manouri:'Manouri',salataxoriatiki:'Greek salad',ntakos:'Dakos',caesar:'Caesar salad',caprese:'Caprese salad',nicoise:'Salade niçoise',waldorf:'Waldorf salad',cobb:'Cobb salad',tabbouleh:'Tabbouleh',fattoush:'Fattoush',panzanella:'Panzanella',shopska:'Shopska salad',rosiki:'Olivier salad',patatosalata:'Potato salad',salatalaxano:'Coleslaw',pastasalata:'Pasta salad',kotosalata:'Chicken salad',
/* πρωινό, συνοδευτικά */
spanakopita:'Spanakopita',tyropita:'Tiropita',mpougatsa:'Bougatsa',koulouri:'Koulouri of Thessaloniki',patatestiganites:'French fries',poures:'Mashed potato',pilafi:'Pilaf',avgolemono:'Avgolemono',mpesamel:'Béchamel sauce',chimichurri:'Chimichurri',avgamatia:'Fried egg',omeleta:'Omelette',strapatsada:'Strapatsada',avgabenedict:'Eggs Benedict',pancakes:'Pancake',vromi:'Porridge',giaourtimeli:'Strained yogurt',avocadotost:'Avocado toast',tiganites:'Tiganites',
/* γλυκά */
mpaklavas:'Baklava',giannotikos:'Baklava',kantaifi:'Kadayıf',ekmek:'Ekmek kadayıfı',galaktompoureko:'Galaktoboureko',ravani:'Revani',samali:'Revani',karydopita:'Karydopita',portokalopita:'Portokalopita',loukoumades:'Loukoumades',diples:'Diples',ryzogalo:'Rice pudding',kremakaramele:'Crème caramel',tiramisu:'Tiramisu',pannacotta:'Panna cotta',cheesecake:'Cheesecake',cheesecakepsito:'Cheesecake',brownies:'Chocolate brownie',melomakarona:'Melomakarono',kourampiedes:'Kourabiedes',tsoureki:'Tsoureki',koulourakia:'Koulourakia',basvasilopita:'Vasilopita',pasteli:'Pasteli',xalvassimigdali:'Halva',xalvastahini:'Halva',profiterol:'Profiterole',soufle:'Molten chocolate cake',krepes:'Crêpe',vafla:'Belgian waffle',ekler:'Éclair',milopita:'Apple pie',cremebrulee:'Crème brûlée',milfeig:'Mille-feuille',blackforest:'Black Forest gâteau',tourtasokolata:'Chocolate cake',tartalemoni:'Lemon meringue pie',keikkarotou:'Carrot cake',keikmpanana:'Banana bread',granita:'Granita',pagotovanilia:'Ice cream',vyssino:'Spoon sweets',loukoumi:"Turkish delight",kiounefe:'Kanafeh',kalitsounia:'Kalitsounia',fanouropita:'Fanouropita',xristopsomo:'Christopsomo',lagana:'Lagana',kydonopasto:'Quince cheese',babas:'Rum baba',korne:'Cream horn',mahalepi:'Muhallebi',moustalevria:'Moustalevria',
/* αποστάγματα */
ouzo:'Ouzo',tsipouro:'Tsipouro',tsikoudia:'Tsikoudia',rakomelo:'Rakomelo',mastiha:'Mastika',kitro:'Kitron',metaxa:'Metaxa',whisky:'Whisky',vodka:'Vodka',gin:'Gin',rum:'Rum',tequila:'Tequila',grappa:'Grappa',limoncello:'Limoncello',amaretto:'Amaretto',baileys:"Baileys Irish Cream",sambuca:'Sambuca',jager:'Jägermeister',vermouth:'Vermouth',campari:'Campari',absinthe:'Absinthe',calvados:'Calvados',sake:'Sake',cachaca:'Cachaça',soju:'Soju',piscospirit:'Pisco',kahlua:'Kahlúa',chartreuse:'Chartreuse (liqueur)',cointreau:'Cointreau',frangelico:'Frangelico',licor43:'Licor 43',koum:'Kumquat',
/* κρασιά */
asyrtiko:'Assyrtiko',moschofilero:'Moschofilero',malagouzia:'Malagousia',roditis:'Roditis',savvatiano:'Savatiano',robola:'Robola',chardonnay:'Chardonnay',sauvignon:'Sauvignon blanc',riesling:'Riesling',agiorgitiko:'Agiorgitiko',xinomavro:'Xinomavro',liatiko:'Liatiko',kotsifali:'Kotsifali',limnio:'Limnio',mavrotragano:'Mavrotragano',cabernet:'Cabernet Sauvignon',merlot:'Merlot',syrah:'Syrah',pinotnoir:'Pinot noir',roze:'Rosé',retsina:'Retsina',prosecco:'Prosecco',champagne:'Champagne',mavrodafni:'Mavrodafni',vinsanto:'Vinsanto',sangiovese:'Sangiovese',chianti:'Chianti',nebbiolo:'Nebbiolo',tempranillo:'Tempranillo',malbec:'Malbec',zinfandel:'Zinfandel',grenache:'Grenache',gewurz:'Gewürztraminer',pinotgrigio:'Pinot gris',porto:'Port wine',sherry:'Sherry',vinhoverde:'Vinho Verde',albarino:'Albariño',
/* μπύρες */
lager:'Lager',pilsner:'Pilsner',helles:'Helles',bock:'Bock',dunkel:'Dunkel',marzen:'Märzen',weiss:'Wheat beer',witbier:'Witbier',paleale:'Pale ale',ipa:'India pale ale',amber:'Amber ale',stout:'Stout',porter:'Porter (beer)',tripel:'Tripel',dubbel:'Dubbel',sour:'Sour beer',kriek:'Kriek lambic',radler:'Shandy',kolsch:'Kölsch (beer)',saison:'Saison',barleywine:'Barley wine',rauchbier:'Rauchbier',michelada:'Michelada',
/* κοκτέιλ */
mojito:'Mojito',virginmojito:'Mojito',margarita:'Margarita',frozenmargarita:'Margarita',tommys:"Tommy's margarita",daiquiri:'Daiquiri',hemingway:'Daiquiri',strawberrydaiquiri:'Daiquiri',negroni:'Negroni',sbagliato:'Negroni',boulevardier:'Boulevardier (cocktail)',americano_ct:'Americano (cocktail)',oldfashioned:'Old fashioned (cocktail)',manhattan:'Manhattan (cocktail)',drymartini:'Martini (cocktail)',vesper:'Vesper (cocktail)',espressomartini:'Espresso martini',whiskeysour:'Whiskey sour',pisco:'Pisco sour',sidecar:'Sidecar (cocktail)',cosmopolitan:'Cosmopolitan (cocktail)',ginttonic:'Gin and tonic',moscowmule:'Moscow mule',darkstormy:"Dark 'n' Stormy",cubalibre:'Rum and Coke',longisland:'Long Island iced tea',bloodymary:'Bloody Mary (cocktail)',virginmary:'Bloody Mary (cocktail)',whiterussian:'White Russian (cocktail)',tomcollins:'Tom Collins',frenchseventyfive:'French 75 (cocktail)',aviation:'Aviation (cocktail)',penicillin:'Penicillin (cocktail)',pinacolada:'Piña colada',virginpina:'Piña colada',maitai:'Mai Tai',zombie:'Zombie (cocktail)',caipirinha:'Caipirinha',tequilasunrise:'Tequila sunrise',paloma:'Paloma (cocktail)',sexonthebeach:'Sex on the Beach',bluelagoon:'Blue Lagoon (cocktail)',pornstar:'Pornstar martini',sangria:'Sangria',mulledwine:'Mulled wine',aperolspritz:'Spritz Veneziano',hugo:'Hugo (cocktail)',bellini:'Bellini (cocktail)',mimosa:'Mimosa (cocktail)',kir:'Kir (cocktail)',bramble:'Bramble (cocktail)',cloverclub:'Clover Club cocktail',mintjulep:'Mint julep',singaporesling:'Singapore Sling',grasshopper:'Grasshopper (cocktail)',alexander:'Brandy Alexander',frenchmartini:'French martini',garibaldi:'Garibaldi (cocktail)',horsesneck:"Horse's Neck",seabreeze:'Sea Breeze (cocktail)',rustynail:'Rusty Nail',sazerac:'Sazerac',junglebird:'Jungle Bird',lastword:'Last Word',lemondrop:'Lemon drop (cocktail)',godfather:'Godfather (cocktail)',b52:'B-52 (cocktail)',kamikaze:'Kamikaze (cocktail)',hottoddy:'Hot toddy',eggnog:'Eggnog',mudslide:'Mudslide (cocktail)',tintoverano:'Tinto de verano',bluehawaiian:'Blue Hawaii (cocktail)',shirleytemple:'Shirley Temple (drink)',rumpunch:'Planter\'s Punch'
};
/* διορθώσεις μετά από έλεγχο (λήμματα χωρίς εικόνα ή ανύπαρκτα) */
Object.assign(WP,{tilio:'Tilia',tbone:'Steak',ribeye:'Steak',tomahawk:'Steak',mparmpounia:'Mullus surmuletus',mydia:'Moules-frites',koulouri:'Simit',mousfalevria:'Moustalevria'});
['kokoraskrasatos','kontosouvli','mpiftekia','soutzoukakia','kokkinisto','giouvarlakia','kakavia','broccolicheddar','arayes','fava','tiganites','ouzo','campari','frangelico','limoncello','lagana','rakomelo','moustalevria','mousfalevria','sherry','robola','malagouzia','limnio','liatiko','mavrotragano','rustynail','lastword','mudslide'].forEach(k=>delete WP[k]);
Object.assign(WP,{paperplane:'-',ginbasil:'-'}); /* '-' = καμία φωτογραφία (αναζήτηση δίνει άσχετα) */
